enum packetType {
    HELLO,
    UPLOAD,
    UPLOAD_INOTIFY,
    UPLOAD_PROPAGATION,
    REQUEST_DOWNLOAD,
    DOWNLOAD,
    DOWNLOAD_ERROR,
    DELETE,
    DELETE_INOTIFY,
    DELETE_PROPAGATION,
    REQUEST_LIST_SERVER,
    LIST_SERVER,
    BYE
};